### ISSUE TITLE
<C-b>: leaves terminal mode, fires empty command

### ISSUE THREAD

**Issue by bzub** [BurningEther/nvimux#18]
https://github.com/BurningEther/nvimux/blob/06a2180bab28eb4013c7e5c0a60a6740d046037b/lua/nvimux.lua#L71

There's an extra `<CR>` on the resulting tnoremap that seems to be the culprit.
```
:tnoremap <C-b>:
   <C-B>:      * <C-\><C-N>:<CR>
```

For the time being I work around it with
`tnoremap <C-B>: <C-\><C-N>:`

**Comment by hkupty** [comment]
Hi, thanks for the issue.

I'll take a look at it immediately!

Cheers,
Henry John Kupty
