### ISSUE TITLE
open-term-by-default not working

### ISSUE THREAD

**Issue by lxndrcx** [BurningEther/nvimux#25]
With config [init.vim](https://github.com/lxndrcx/neovim-init.vim/blob/master/init.vim)
nvimux works well, except that it does not seem to respect `open-term-by-default = true`.
When I type `<C-a>c` I just get an empty file buffer. Have I done something wrong?

**Comment by lxndrcx** [comment]
I have updated the [init.vim](https://github.com/lxndrcx/neovim-init.vim/blob/master/init.vim) and pulled the latest nvimux changes, and now I am getting this error on startup:
```
Error detected while processing /Users/alexc/.config/nvim/init.vim:
line  135:
E5105: Error while calling lua chunk: ...s/alexc/.local/share/nvim/plugged/nvimux//lua/nvimux.lua:85: attempt to concatenate field 'new_tab' (a nil value)
```
When I change it to `new_tab ='term'` nvimux starts and works as expected, with new windows and tabs opening a terminal.

**Comment by lxndrcx** [comment]
Also note that you have not updated the VimL configuration in the Readme.md, it still says `g:nvimux_open_term_by_default` but should say `g:nvimux_new_window` and `g:nvimux_new_tab`

**Comment by hkupty** [comment]
I removed the `new_tab` for now.. I'll look into it for in more details later on, but it should be working (while not as expected) by setting `new_window` to `term`
