### ISSUE TITLE
Custom keybindings | and -

### ISSUE THREAD

**Issue by wreed4** [BurningEther/nvimux#30]
Hi, first, great plugin.  I've only been playing with it a bit, but it seems awesome. I'm trying to use it in conjunction with the Oni editor to somewhat replace my nvim in tmux setup with a tmux in nvim setup.  Seems awesome. 

Secondly, I'm trying to map all my tmux mappings the same and for splits I use `|` for vertical and `-` for horizontal.  So, I replaced the suggested `s` and `v` mappings with 
```lua
nvimux.bindings.bind_all{
  {'-', ':NvimuxHorizontalSplit', {'n', 'v', 'i', 't'}},
  {'|', ':NvimuxVerticalSplit', {'n', 'v', 'i', 't'}},
}
```
I don't know lua at all, but this seems to cause some kind of error within the plugin.  I'm getting the following error: 
```
Error detected while processing /home/william/.dotfiles/vim/init.vim: line 544: E5105: Error while calling lua chunk: /home/william/.vim/bundle/nvimux//lua/nvimux.lua:114: Keyboard interrupt
```
Any help debugging this would be very appreciated.

**Comment by wreed4** [comment]
Iiiiiii take it back.  For anyone seeing this in the future, these bindings are just placed into a vim `noremap`.  `|` is obviously a special character interpreted by neovim. So to correctly bind `|` to something in this plugin, you have to double escape it

```lua
nvimux.bindings.bind_all{
  {'-', ':NvimuxHorizontalSplit', {'n', 'v', 'i', 't'}},
  {'\\|', ':NvimuxVerticalSplit', {'n', 'v', 'i', 't'}},
}
```

solved.

**Comment by hkupty** [comment]
Hah! You were faster than me! Thanks for the issue, I realy appreciate it.

Glad that you like nvimux! Feel free to come by if you have any doubts or issues again.

Cheers,
Henry John Kupty
